plugins:
  - jekyll-paginate

title: One hour study
description: Study an hour every day

url                      : https://karma822.github.io
baseurl                  : "/Onehourstudy"

paginate: 10
paginate_path: /page/:num/
permalink: /:title/
